In [1]:
print("hello owrld")

hello owrld


NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays.

It is the fundamental package for scientific computing with Python. It contains various features including these important ones:

        A powerful N-dimensional array object
        Sophisticated (broadcasting) functions
        Tools for integrating C/C++ and Fortran code
        Useful linear algebra, Fourier transform, and random number capabilities
        Technique for effectively loading, storing and manipulating data in python.


        Efficient storage and manipulation of numerical arrays is absolutely fundamental to the process of doing Data Science
        Specialized tools that python has for handling such numerical arrays
        Numpy Package
        Pandas Package

# Why Numpy Instead if List

        Less Memory
        Fast
        Convenient


# List


In [4]:
import numpy as np
import time
import sys
s =range(1000)
print(sys.getsizeof(5)*len(s))

28000


# Numpy


In [5]:
import numpy as np
D = np.arange(1000)
print(D.size*D.itemsize)

4000


In [14]:
import time
n1 = time.time()
print(n1)

1705654248.5789433


In [4]:
import time 

dir(time.time())

['__abs__',
 '__add__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getformat__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__le__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmod__',
 '__rmul__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 'as_integer_ratio',
 'conjugate',
 'fromhex',
 'hex',
 'imag',
 'is_integer',
 'real']

In [5]:
print(time.ctime())

Sun Jan 21 21:16:59 2024


In [6]:
print(time.gmtime())

time.struct_time(tm_year=2024, tm_mon=1, tm_mday=21, tm_hour=15, tm_min=48, tm_sec=1, tm_wday=6, tm_yday=21, tm_isdst=0)


In [25]:
# print(time.timezone()),
# print(time.daylight()),
# print(time.get_clock_info()),
# print(time.mktime()),
print(time.time_ns())
# print(time.tzname())
# print(time.mktime())
print(time.asctime())
print(time.time())
print(time.ctime())


1705852594769204800
Sun Jan 21 21:26:34 2024
1705852594.7692049
Sun Jan 21 21:26:34 2024


In [12]:
import numpy as np
import time
SIZE=100000
L1=range(SIZE)
L2=range(SIZE)
A1=np.arange(SIZE)
A2=np.arange(SIZE)
start=time.time()
result=[(x,y) for x,y in zip(L1,L2)]
print((time.time()-start)*1000)
start=time.time()
result=A1+A2
print((time.time()-start)*1000)


133.17203521728516
10.021448135375977


In [13]:
import numpy as np
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
print("Array is of type: ", type(arr))
print("No. of dimensions: ", arr.ndim)
print("Shape of array: ", arr.shape)
print("Size of array: ", arr.size)
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32


# Array Creation:

To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists.

For example: np.zeros, np.ones, np.full, np.empty, etc.

arange: returns evenly spaced values within a given interval. step size is specified.

linspace: returns evenly spaced values within a given interval. num no. of elements are returned.

Reshaping array: We can use reshape method to reshape an array. Consider an array with shape (a1, a2, a3, …, aN). We can reshape and convert it into another array with shape (b1, b2, b3, …, bM). The only required condition is:a1 x a2 x a3 … x aN = b1 x b2 x b3 … x bM . (i.e original size of array remains unchanged.)

Flatten array: We can use flatten method to get a copy of array collapsed into one dimension. It accepts order argument. Default value is ‘C’ (for row-major order). Use ‘F’ for column major order.

In [26]:
import numpy as np
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float')
print ("Array created using passed list:\n", a)
b = np.array((1 , 3, 2))
# print(type(b))
print ("\nArray created using passed tuple:\n", b)
c = np.zeros((3, 4))
print ("\nAn array initialized with all zeros:\n", c)
d = np.full((3, 3), 6, dtype = 'complex')
print ("\nAn array initialized with all 6s." 
            "Array type is complex:\n", d)
e = np.random.random((2, 2))
print ("\nA random array:\n", e)
f = np.arange(0, 30, 5)
print ("\nA sequential array with steps of 5:\n", f)



Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]
<class 'numpy.ndarray'>

Array created using passed tuple:
 [1 3 2]

An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

An array initialized with all 6s.Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]

A random array:
 [[0.79596618 0.3747423 ]
 [0.21550777 0.55602345]]

A sequential array with steps of 5:
 [ 0  5 10 15 20 25]


 Array Indexing: Knowing the basics of array indexing is important for analysing and manipulating the array object. NumPy offers many ways to do array indexing

Slicing: Just like lists in python, NumPy arrays can be sliced. As arrays can be multidimensional, you need to specify a slice for each dimension of the array. 

Integer array indexing: In this method, lists are passed for indexing for each dimension. One to one mapping of corresponding elements is done to construct a new arbitrary array.

Boolean array indexing: This method is used when we want to pick elements from array which satisfy some condition.
import numpy as np



In [27]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

temp = arr[:2, ::2]


print ("Array with first 2 rows and alternate"
                    "columns(0 and 2):\n", temp)


Array with first 2 rows and alternatecolumns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]


In [28]:
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),"
                                    "(3, 0):\n", temp)
cond = arr > 0 
temp = arr[cond]
print ("\nElements greater than 0:\n", temp)


Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4. 6. 0. 3.]

Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


In [18]:
print ("Array with first 2 rows and alternate"
                    "columns(0 and 2):\n", temp)
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),"
                                    "(3, 0):\n", temp)
cond = arr > 0 
temp = arr[cond]
print ("\nElements greater than 0:\n", temp)

Array with first 2 rows and alternatecolumns(0 and 2):
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]

Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4. 6. 0. 3.]

Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


# BASIC OPERATIONS


In [19]:
import numpy as np
a = np.array([1, 2, 5, 3])
print ("Adding 1 to every element:", a+1)
print ("Subtracting 3 from each element:", a-3)
print ("Multiplying each element by 10:", a*10)
print ("Squaring each element:", a**2)
a *= 2
print ("Doubled each element of original array:", a)
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
print ("\nOriginal array:\n", a)
print ("Transpose of array:\n", a.T)

Adding 1 to every element: [2 3 6 4]
Subtracting 3 from each element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


# Numpy sum with axis 0, means Cloumns


In [30]:
import numpy as np
np_array_2d = np.arange(0, 6).reshape([2,3])
print(np_array_2d, '\n\n')
a = np.sum(np_array_2d, axis = 0)
print(a)

[[0 1 2]
 [3 4 5]] 


[3 5 7]


# Numpy Sum With Axis 1 means rows


In [32]:
import numpy as np
np_array_2d = np.arange(0, 6).reshape([2,3])
print(np_array_2d, '\n\n')
a = np.sum(np_array_2d, axis = 1)
print(a)

[[0 1 2]
 [3 4 5]] 


[ 3 12]


# Concatenate Np arrays with axis 0


In [33]:
import numpy as np
np_array_1 = np.array([[1,1,1],[1,1,1]])
np_array_2 = np.array([[2,2,2],[2,2,2]])
print(np_array_1, '\n')
print(np_array_2, '\n\n')
a = np.concatenate([np_array_1, np_array_2], axis = 0)
print(a)

[[1 1 1]
 [1 1 1]] 

[[2 2 2]
 [2 2 2]] 


[[1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]]


# Concatenate Numpy arrays with axis 1


In [34]:
import numpy as np
np_array_1 = np.array([[1,1,1],[1,1,1]])
np_array_2 = np.array([[2,2,2],[2,2,2]])
print(np_array_1, '\n')
print(np_array_2, '\n\n')
a = np.concatenate([np_array_1, np_array_2], axis = 1)
print(a)


[[1 1 1]
 [1 1 1]] 

[[2 2 2]
 [2 2 2]] 


[[1 1 1 2 2 2]
 [1 1 1 2 2 2]]


# Example to concatenate two 1D arrays with Np axis in python


In [42]:
import numpy as np
np_array_1 = np.array([1,1,1])
np_array_2 = np.array([2,2,2])
print(np_array_1, '\n')
print(np_array_2, '\n')
a = np.concatenate([np_array_1, np_array_2], axis = 0)
print(a)

# b = np.concatenate([np_array_1, np_array_2], axis = 1)
# print(b)


a= np.vstack([np_array_1, np_array_2 ])

print(a, '\n\n')
b= np.hstack([np_array_1, np_array_2 ])
print(b)

[1 1 1] 

[2 2 2] 

[1 1 1 2 2 2]
[[1 1 1]
 [2 2 2]] 


[1 1 1 2 2 2]
