In [1]:
print("hello world")

hello world


# Join, Split, Search, Sort, Filter

In [30]:
# import numpy as np

# help(np.char.join)

## Join

The join() function is used to add a separator character or string to any given string or to all the elements of the given array of strings. 

If you have a string "STUDY" and you want to use "-" as separator character, then using the join() function the output will be "S-T-U-D-Y".

This function basically calls str.join function internally on every element of the array.

Syntax of numpy.char.join():
The syntax required to use this function is as follows:

		numpy.char.join(sep, seq)
The above syntax indicates that join() function takes two parameters.

### parameters

sep
This argument represents an array of string/characters used as the separator characters.

seq
This argument indicates the input array or string on which the operation will be performed.

Returned Values:

This function returns an output array of either string or Unicode with the joined elements.

# Example -1

In [4]:
import numpy as np
   
a = np.char.join(':','DG')
print("The Joined string in the output:")
print(a)

# a = np.char.join(':','DGJSDFHKJDSFHK')
# print("The Joined string in the output:")
# print(a)

The Joined string in the output:
D:G


# Example -2

With an Array of String

We will use join() function on the array of strings with unique separator for each string element of the array.

In [6]:
import numpy as np

inp = np.array(['Apple', 'Python', 'NumPy','StudyTonight']) 
print ("The original Input array : \n", inp) 

sep = np.array(['^', '+', '*','-']) 

output= np.char.join(sep, inp) 
print ("The Output joined array: ", output) 

The original Input array : 
 ['Apple' 'Python' 'NumPy' 'StudyTonight']
The Output joined array:  ['A^p^p^l^e' 'P+y+t+h+o+n' 'N*u*m*P*y' 'S-t-u-d-y-T-o-n-i-g-h-t']


# Example -3

In this example, we will use a single separator string for all the string elements of the given array.

In [7]:
import numpy as np

inp = np.array(['Apple', 'Python', 'NumPy','StudyTonight']) 
print ("The original Input array : \n", inp) 

sep = np.array(['^^^']) 

output= np.char.join(sep, inp) 
print ("The Output joined array: ", output) 

The original Input array : 
 ['Apple' 'Python' 'NumPy' 'StudyTonight']
The Output joined array:  ['A^^^p^^^p^^^l^^^e' 'P^^^y^^^t^^^h^^^o^^^n' 'N^^^u^^^m^^^P^^^y'
 'S^^^t^^^u^^^d^^^y^^^T^^^o^^^n^^^i^^^g^^^h^^^t']


# Split


The split() function is used to return a list of strings after breaking the input string by the specified separator(sep).

This function usually calls str.split internally on every element of the array.

Syntax of numpy.char.split():
The syntax required to use this function is as follows:

	numpy.char.split(a, sep=None, maxsplit=None)

The above syntax indicates that split() function takes two parameters.

Parameters:


a
This parameter indicates the input string or the input array of strings

sep
It can be string or Unicode(single character). If sep is not specified or it is None then by default the whitespace string is used as a separator.

maxsplit
It is an integer and If it is given, at most maxsplit splits are done.

Returned Values:

This function will return an array of the list of splitted string values as an output.


In [29]:
# help(np.char.split)

### Example 1: With a simple string

In [8]:
import numpy as np

a = "How you doing?"
print("The input is :\n",a)

y = np.char.split(a)
print("after applying split() method output is:\n",y)


# a = "How you doing? hia hello welcometo the world ofengin eering"
# print("The input is :\n",a)

# y = np.char.split(a)
# print("after applying split() method output is:\n",y)

The input is :
 How you doing?
after applying split() method output is:
 ['How', 'you', 'doing?']


### Example 2: With maxsplit Parameter

We will use the maxsplit parameter of the split() function. We will try to split the given string based on comma(,) and you will see although there are 2 commas in the complete string, the string will be split only once, because we have provided the maxsplit parameter value as 1.

In [23]:
import numpy as np

x = "We, very happily, welcome you all!"
print("The String is:\n", x)

out = np.char.split(x, sep=',', maxsplit=1)
print("The output is:", out)

# out = np.char.split(x, sep=',', maxsplit=2)
# print("The output is:", out)


# out = np.char.split(x, maxsplit=3)
# print("The output is:", out)


# out = np.char.split(x, maxsplit=5)
# print("The output is:", out)

The String is:
 We, very happily, welcome you all!
The output is: ['We', ' very happily, welcome you all!']


### Example 3: With array of string

We will apply the split() method on an array of strings.

In [26]:
import numpy as np

inp = np.array(['Dance-Tonight', 'Sleep-Tonight', 'Walk-Tonight','Study-Tonight']) 
print ("The original Input array : \n", inp) 

output= np.char.split(inp, sep='-', maxsplit=1)
print ("The output split array: ", output)


# inp1 = np.array('Dance-Tonight Sleep-Tonight Walk-Tonight Study-Tonight') 
# print ("The original Input array : \n", inp1) 

# output= np.char.split(inp1, sep='-', maxsplit=1)
# print ("The output split array: ", output)



# inp1 = np.array('Dance-Tonight Sleep-Tonight Walk-Tonight Study-Tonight') 
# print ("The original Input array : \n", inp1) 

# output= np.char.split(inp1, sep='-', maxsplit=3)
# print ("The output split array: ", output)


The original Input array : 
 ['Dance-Tonight' 'Sleep-Tonight' 'Walk-Tonight' 'Study-Tonight']
The output split array:  [list(['Dance', 'Tonight']) list(['Sleep', 'Tonight'])
 list(['Walk', 'Tonight']) list(['Study', 'Tonight'])]
The original Input array : 
 Dance-Tonight Sleep-Tonight Walk-Tonight Study-Tonight
The output split array:  ['Dance', 'Tonight Sleep', 'Tonight Walk', 'Tonight Study-Tonight']


In [33]:
# help(np.where)

# Search

We can search for a specific value using the numpy.where() method. This method returns the index where the specific element is found.


In [31]:
import numpy as np
n = np.array([10, 20, 30, 40, 50, 30])
print(n)
print("Iterating array...")
for a in n:
    print(a)
res = np.where(n == 30)
print("\nElement 30 found at following indexes:")
print(res)

[10 20 30 40 50 30]
Iterating array...
10
20
30
40
50
30

Element 30 found at following indexes:
(array([2, 5], dtype=int64),)


In [35]:
# help(np.sort)

# Sort

We require a sorted array for computation. For this purpose, the numpy module of Python provides a function called numpy.sort(). This function gives a sorted copy of the source array or input array.

Syntax:
	numpy.sort(a, axis=-1, kind='quicksort', order=None)  
Parameters:
	x: array_like

This parameter defines the source array, which is going to be sorted.

Example 1:


In [37]:
import numpy as np  
x=np.array([[1,4,2,3],[9,13,61,1],[43,24,88,22]])  
print(x, '\n')  
y=np.sort(x)  
print(y) 

[[ 1  4  2  3]
 [ 9 13 61  1]
 [43 24 88 22]] 

[[ 1  2  3  4]
 [ 1  9 13 61]
 [22 24 43 88]]


Example 2:


In [39]:
import numpy as np  
x=np.array([[1,4,2,3],[9,13,61,1],[43,24,88,22]])  
print(x, '\n')  
y=np.sort(x, axis=None)  
print(y) 

[[ 1  4  2  3]
 [ 9 13 61  1]
 [43 24 88 22]] 

[ 1  1  2  3  4  9 13 22 24 43 61 88]


Example 3:


In [41]:
import numpy as np  
x=np.array([[1,4,2,3],[9,13,61,1],[43,24,88,22]])  
print(x, '\n')  
y=np.sort(x,axis=0)  
print(y, '\n')  
z=np.sort(x,axis=1)  
print(z) 

[[ 1  4  2  3]
 [ 9 13 61  1]
 [43 24 88 22]] 

[[ 1  4  2  1]
 [ 9 13 61  3]
 [43 24 88 22]] 

[[ 1  2  3  4]
 [ 1  9 13 61]
 [22 24 43 88]]


Example 4:



In [43]:
import numpy as np  
dtype = [('name', 'S10'), ('height', float), ('age', int),('gender','S10')]  
values = [('Shubham', 5.9, 23, 'M'), ('Arpita', 5.6, 23, 'F'),('Vaishali', 5.2, 30, 'F')]  
x=np.array(values, dtype=dtype)  
print(x, '\n')  
y=np.sort(x, order='age')  
print(y, '\n')  
z=np.sort(x, order=['age','height'])  
print(z, '\n') 


[(b'Shubham', 5.9, 23, b'M') (b'Arpita', 5.6, 23, b'F')
 (b'Vaishali', 5.2, 30, b'F')] 

[(b'Arpita', 5.6, 23, b'F') (b'Shubham', 5.9, 23, b'M')
 (b'Vaishali', 5.2, 30, b'F')] 

[(b'Arpita', 5.6, 23, b'F') (b'Shubham', 5.9, 23, b'M')
 (b'Vaishali', 5.2, 30, b'F')] 



In [ ]:
help(np.filter)

# Filter

Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

A boolean index list is a list of booleans corresponding to indexes in the array.

If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

Method 1: Filter Values Based on One Condition

#filter for values less than 5

my_array[my_array < 5]

Method 2: Filter Values Using “OR” Condition

#filter for values less than 5 or greater than 9
my_array[(my_array < 5) | (my_array > 9)]

Method 3: Filter Values Using “AND” Condition

#filter for values greater than 5 and less than 9
my_array[(my_array > 5) & (my_array < 9)]

Method 4: Filter Values Contained in List

#filter for values that are equal to 2, 3, 5, or 12
my_array[np.in1d(my_array, [2, 3, 5, 12])]

# Try to use this code.

In NumPy, you can use boolean indexing as a way to filter elements from an array based on a certain condition. Here's a simple example demonstrating how to use boolean indexing to filter elements:

In [45]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Define a condition to filter elements (e.g., elements greater than 5)
condition = arr > 5

# Use boolean indexing to filter elements based on the condition
filtered_arr = arr[condition]

# Print the original array
print("Original array:")
print(arr)

# Print the filtered array
print("\nFiltered array (elements greater than 5):")
print(filtered_arr)


Original array:
[ 1  2  3  4  5  6  7  8  9 10]

Filtered array (elements greater than 5):
[ 6  7  8  9 10]


In this example, arr > 5 creates a boolean array where each element is True if the corresponding element in arr is greater than 5 and False otherwise. This boolean array is then used for boolean indexing, which selects only the elements from the original array that correspond to True values in the boolean array.

You can customize the condition based on your specific filtering criteria. Boolean indexing provides a flexible and efficient way to filter elements in NumPy arrays.

# In Pandas, you can use boolean indexing to filter rows from a DataFrame based on a certain condition. Here's an example:

In [49]:
import pandas as pd

# Create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Emily'],
        'Age': [25, 30, 22, 35, 28],
        'Salary': [50000, 60000, 45000, 70000, 55000]}

df = pd.DataFrame(data)

# Display the original DataFrame
print("Original DataFrame:")
print(df)

# Define a condition to filter rows (e.g., rows with Age greater than 25)
condition = df['Age'] > 25

# Use boolean indexing to filter rows based on the condition

# filtered_df = df[condition]

# or

filtered_df = df[df['Age']> 25]

# Display the filtered DataFrame
print("\nFiltered DataFrame (rows with Age greater than 25):")
print(filtered_df)


Original DataFrame:
      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   22   45000
3    David   35   70000
4    Emily   28   55000

Filtered DataFrame (rows with Age greater than 25):
    Name  Age  Salary
1    Bob   30   60000
3  David   35   70000
4  Emily   28   55000


In this example, df['Age'] > 25 creates a boolean Series where each element is True if the corresponding age is greater than 25 and False otherwise. This boolean Series is then used for boolean indexing, which selects only the rows from the original DataFrame where the condition is True.

You can customize the condition based on your specific filtering criteria. Boolean indexing is a powerful feature in Pandas for filtering and selecting data based on conditions.