In [1]:
print("hello world")

hello world


# Advanced indexing and iterating over array.

# Advanced indexing.

In [3]:
import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
print('Our array is:' )
print(x )
print('\n') 
rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]]) 
y = x[rows,cols] 
print('The corner elements of this array are:' )
print(y)

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The corner elements of this array are:
[[ 0  2]
 [ 9 11]]


In [10]:
import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
print ('Our array is:') 
print (x )
print()
print ('\n' )


Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]





In [11]:
z = x[1:4,1:3] 
print ('After slicing, our array becomes:' )
print (z )
print ('\n' )
y = x[1:4,[1,2]] 
print ('Slicing using advanced index for column:' )
print( y)


After slicing, our array becomes:
[[ 4  5]
 [ 7  8]
 [10 11]]


Slicing using advanced index for column:
[[ 4  5]
 [ 7  8]
 [10 11]]


# indexing over array

NumPy package contains an iterator object numpy.nditer. It is an efficient multidimensional iterator object using which it is possible to iterate over an array. 

Each element of an array is visited using Python’s standard Iterator interface.

Let us create a 3X4 array using arange() function and iterate over it using nditer.

In [12]:
import numpy as np
a = np.arange(0,60,5)
print(a)
a = a.reshape(3,4)
print ('Original array is:')
print (a)
print ('\n')
print ('Modified array is:')
for x in np.nditer(a):
   print (x,)

[ 0  5 10 15 20 25 30 35 40 45 50 55]
Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
0
5
10
15
20
25
30
35
40
45
50
55


Here, np.nditer(a) allows you to iterate over the elements of the 2D array a in a flattened manner (row-wise by default). The loop then prints each element of the array.

In [7]:
import numpy as np 
a = np.arange(0,60,5) 
a = a.reshape(3,4)  
print('Original array is:')
print(a) 
print('\n')
print('Transpose of the original array is:' )
b = a.T 
print(b)
print('\n')
print('Modified array is:') 
for x in np.nditer(b): 
   print(x,)


Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Transpose of the original array is:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


Modified array is:
0
5
10
15
20
25
30
35
40
45
50
55


In [8]:
import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)
print ('Original array is:')
print (a)
print ('\n')
print ('Transpose of the original array is:')
b = a.T
print (b)
print ('\n')
print ('Sorted in C-style order:')



Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Transpose of the original array is:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


Sorted in C-style order:


In [9]:
c = b.copy(order = 'C')
print (c)
for x in np.nditer(c):
   print (x,)
print ('\n')
print ('Sorted in F-style order:')
c = b.copy(order = 'F')
print (c)
for x in np.nditer(c):
   print (x,)


[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0
20
40
5
25
45
10
30
50
15
35
55


Sorted in F-style order:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0
5
10
15
20
25
30
35
40
45
50
55


In C-style order, the elements are iterated over in row-major order (along the last axis), 

while in F-style order, the iteration is in column-major order (along the first axis).

 The printed results demonstrate the difference in iteration order.

# Modifying Array Values.

The nditer object has another optional parameter called op_flags. Its default value is read-only, but can be set to read-write or write-only mode. This will enable modifying array elements using this iterator.

In [11]:
import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)
print ('Original array is:')
print(a)
print ('\n')
for x in np.nditer(a, op_flags = ['readwrite']):
   x[...] = 2*x
print ('Modified array is:')
print (a)



Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


In the line x[...] = 2 * x, the expression x[...] is a shorthand for assigning values to all elements in the current iteration of the np.nditer loop. It's a convenient way to update the array in place.

Here's a breakdown of what's happening:

    x is an iterator that points to the current element in the array during each iteration of the loop.
    x[...] is a slice that represents the entire array element at the current iteration.
    2 * x is the result of multiplying the current element by 2.

So, x[...] = 2 * x is essentially saying "replace the current element with its value multiplied by 2" for each iteration of the loop. This operation is performed in-place, directly modifying the original array a.

In simpler terms, it's a concise way to perform element-wise multiplication of the array by 2.

In [13]:
import numpy as np 
a = np.arange(0,60,5) 
a = a.reshape(3,4) 
print('Original array is:')
print(a) 
print('\n' )
print('Modified array is:')
for x in np.nditer(a, flags = ['external_loop'], order = 'F'):
   print(x),


Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
[ 0 20 40]
[ 5 25 45]
[10 30 50]
[15 35 55]


In this code, the np.nditer is used with flags=['external_loop'] to iterate over the array using an external loop, and the order='F' parameter specifies Fortran-style order. This means that the iteration is done column-wise (along the first axis, in this case, columns) rather than row-wise.

The loop variable x now represents a view of the entire column at each iteration, and it prints the columns one by one.

in other wise it is called transpose matrix.

# Broadcasting Iteration

        If two arrays are broadcastable, a combined nditer object is able to iterate upon them concurrently. 

        Assuming that an array a has dimension 3X4, and there is another array b of dimension 1X4, the iterator of following type is used (array b is broadcast to size of a).

In [14]:
import numpy as np 
a = np.arange(0,60,5) 
a = a.reshape(3,4) 
print ('First array is:')
print (a)
print ('\n' ) 
print ('Second array is:')
b = np.array([1, 2, 3, 4], dtype = int) 
print (b)
print ('\n')
print ('Modified array is:' )
for x,y in np.nditer([a,b]): 
   print ("%d:%d" % (x,y),)

First array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Second array is:
[1 2 3 4]


Modified array is:
0:1
5:2
10:3
15:4
20:1
25:2
30:3
35:4
40:1
45:2
50:3
55:4


In each iteration of the loop, x takes values from the elements of array a, and y takes values from the elements of array b. The %d:%d format is used to print the corresponding elements from both arrays in the form a_element:b_element. The loop iterates through both arrays simultaneously, pairing elements from each array in each iteration.