In [1]:
print("hello world")

hello world


# Stacking and Broadcasting

### Stacking

The numpy.stack() function is used to join a sequence of arrays along a new axis.

The axis parameter specifies the index of the new axis in the dimensions of the result.

 For example, if axis=0 it will be the first dimension and if axis=-1 it will be the last dimension.

numpy.stack() is useful when working with machine learning models that require a single input array. 

For example, when working with image data, it is common to have multiple image files that need to be joined into a single array for processing by the machine learning model.


Syntax:

numpy.stack(arrays, axis=0, out=None)

Stacking arrays vertically using numpy.stack() function

A simple code for numpy stacking:

Array stacking in NumPy involves combining multiple arrays along a new axis. Here's a simple example using np.stack to stack two arrays:



In [2]:
import numpy as np

# Create two arrays with the same shape (3x4)
array1 = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

array2 = np.array([[13, 14, 15, 16],
                   [17, 18, 19, 20],
                   [21, 22, 23, 24]])

# Stack the arrays along a new axis (axis=0)
stacked_array = np.stack([array1, array2], axis=0)

# Print the original arrays and the result
print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nResult after stacking along axis 0:")
print(stacked_array)



Array 1:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array 2:
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

Result after stacking along axis 0:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In this example, np.stack([array1, array2], axis=0) stacks the two arrays along a new axis (axis=0), resulting in a 3D array with shape (2, 3, 4). The first dimension (2) corresponds to the number of arrays stacked, and the remaining dimensions match the shape of the individual arrays.

In [3]:
stacked_array = np.stack([array1, array2], axis=1)

print("\nResult after stacking along axis 1:")
print(stacked_array)



Result after stacking along axis 1:
[[[ 1  2  3  4]
  [13 14 15 16]]

 [[ 5  6  7  8]
  [17 18 19 20]]

 [[ 9 10 11 12]
  [21 22 23 24]]]


        the resulting stacked_array has a shape of (3, 2, 4). The first dimension (3) corresponds to the number of arrays stacked, the second dimension (2) corresponds to the new axis along which the arrays are stacked, and the third dimension (4) matches the shape of the individual arrays.

In [4]:
# import numpy as np

# # Create two arrays with the same shape (3x4)
# array1 = np.array([[1, 2, 3, 4],
#                    [5, 6, 7, 8],
#                    [9, 10, 11, 12]])

# array2 = np.array([[13, 14, 15, 16],
#                    [17, 18, 19, 20],
#                    [21, 22, 23, 24]])

# # Stack the arrays along a new axis, flattening them first
# stacked_array = np.stack([array1, array2], axis=None)

# # Print the original arrays and the result
# print("Array 1:")
# print(array1)

# print("\nArray 2:")
# print(array2)

# print("\nResult after stacking along axis (flattened):")
# print(stacked_array)


It seems I made an error in my explanation. You are correct; using axis=None is not valid, and it results in a TypeError.

If you want to flatten the arrays and then stack them into a 1D array, you can use np.concatenate with ravel():

In [5]:
import numpy as np

# Create two arrays with the same shape (3x4)
array1 = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

array2 = np.array([[13, 14, 15, 16],
                   [17, 18, 19, 20],
                   [21, 22, 23, 24]])

# Concatenate the flattened arrays
stacked_array = np.concatenate([array1.ravel(), array2.ravel()])

# Print the original arrays and the result
print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nResult after concatenating (flattened):")
print(stacked_array)


Array 1:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array 2:
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

Result after concatenating (flattened):
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


        the ravel() function is used to flatten each 2D array (array1 and array2) into a 1D array. The purpose of flattening is to transform a multi-dimensional array into a one-dimensional array, where elements are arranged in a continuous sequence.

Here's a breakdown of the relevant portion of the code:

stacked_array = np.concatenate([array1.ravel(), array2.ravel()])


    array1.ravel() and array2.ravel() both use the ravel() function to flatten the 2D arrays into 1D arrays.

    np.concatenate is then used to concatenate (join) these flattened arrays along a new axis (by default, along the first axis, which is axis 0).

The final result, stacked_array, is a 1D array that contains all the elements from array1 followed by all the elements from array2. The ravel() function is not strictly necessary in this case because np.concatenate can handle arrays of different dimensions. However, using ravel() explicitly emphasizes the intent to flatten the arrays, making the code more readable.

Here's a simplified version without ravel():

np.stack([array1, array2], axis=0) stacks the two arrays along a new axis (axis=0), resulting in a 3D array with shape (2, 3, 4). The first dimension (2) corresponds to the number of arrays stacked, and the remaining dimensions match the shape of the individual arrays.

You can customize the axis parameter to stack arrays along different axes if needed.

In [6]:
stacked_array = np.concatenate([array1, array2])
print(stacked_array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In this case, np.concatenate will concatenate the arrays along the first axis, effectively stacking them. However, it's common to use ravel() explicitly when flattening is intended for clarity and consistency in code.

In [7]:
import numpy as np
arrays = [np.random.randn(2, 3)for _ in range(8)]
print(arrays, '\n')
np.stack(arrays, axis=0).shape
# print(arrays)

[array([[ 0.70441472, -0.54609821,  0.44750943],
       [-0.98281514, -0.27608061,  0.94636634]]), array([[-0.27453956,  1.04850203, -1.04089301],
       [ 2.11758993, -0.59995804,  1.07586468]]), array([[ 0.14104848,  0.05565059, -1.27894081],
       [-0.49064575, -1.24915707,  0.78370247]]), array([[ 1.02816406,  1.15845943,  1.53145429],
       [-1.88272344,  0.32883742, -0.1906882 ]]), array([[ 0.03382039, -0.81699031, -0.7912297 ],
       [-0.69411391, -0.2709025 , -1.26786448]]), array([[ 0.41087988,  1.31904724, -0.41633712],
       [-0.49054015,  0.16545945,  0.39043029]]), array([[ 1.94764435, -0.39350142,  0.01720242],
       [-0.87934485,  1.01299382,  1.35483044]]), array([[ 1.33438361,  0.83421683,  0.20933603],
       [-0.08606883,  0.64320563, -0.31524201]])] 



(8, 2, 3)

    np.stack(arrays, axis=1).shape:

    This line uses np.stack to stack the arrays in the list arrays along axis 1. The resulting shape is (2, 8, 3). This means that there are 2 arrays, each with a shape of (8, 3).

    np.stack(arrays, axis=2).shape:

    This line uses np.stack to stack the arrays along axis 2. The resulting shape is (2, 3, 8). This means that there are 2 arrays, each with a shape of (3, 8).

    x = np.array([2, 3, 4]), y = np.array([3, 4, 5]), and np.stack((x, y)):

    These lines create two 1D arrays x and y, each with length 3. Then, np.stack((x, y)) stacks them along a new axis (axis 0 by default), resulting in a 2D array with shape (2, 3).

In [15]:
import numpy as np

# Create a list of arrays (each with shape (8, 3))
arrays = [np.random.randn(8, 3) for _ in range(2)]

# Stack arrays along axis 1
result1 = np.stack(arrays, axis=1)
print("Result after stacking along axis 1:")
print(result1)
print("Shape:", result1.shape)

# Stack arrays along axis 2
result2 = np.stack(arrays, axis=2)
print("\nResult after stacking along axis 2:")
print(result2)
print("Shape:", result2.shape)

# Create two 1D arrays
x = np.array([2, 3, 4])
y = np.array([3, 4, 5])

# Stack the 1D arrays along a new axis (axis 0 by default)
result3 = np.stack((x, y))
print("\nResult after stacking 1D arrays:")
print(result3)
print("Shape:", result3.shape)


Result after stacking along axis 1:
[[[ 0.81596639  0.08288185  0.35452261]
  [-0.40596768  0.82165221  0.13750855]]

 [[ 0.47914798  2.15075397  0.41630258]
  [ 0.03185539  1.18274166 -0.5985299 ]]

 [[-2.43476854  0.95867049  0.53105052]
  [-0.48755728  1.00365481 -0.59474492]]

 [[ 1.06110246 -0.96649869  0.93683857]
  [ 1.09816886  0.45909041  0.5034984 ]]

 [[-0.85334095  0.28559004 -0.67370684]
  [-0.29724123 -0.485882    1.87240289]]

 [[-0.3983351   0.21528958  0.82444597]
  [-0.19914722  0.48586121 -1.43015485]]

 [[-0.69736551 -0.23597564 -0.62315131]
  [ 1.92398084 -0.03109553 -0.4822946 ]]

 [[ 0.42057222  0.13862526 -0.14532714]
  [ 0.29600163 -1.18656442  0.35256764]]]
Shape: (8, 2, 3)

Result after stacking along axis 2:
[[[ 0.81596639 -0.40596768]
  [ 0.08288185  0.82165221]
  [ 0.35452261  0.13750855]]

 [[ 0.47914798  0.03185539]
  [ 2.15075397  1.18274166]
  [ 0.41630258 -0.5985299 ]]

 [[-2.43476854 -0.48755728]
  [ 0.95867049  1.00365481]
  [ 0.53105052 -0.59474492

    np.stack(arrays, axis=1).shape:
        Stacking along axis 1 combines the arrays along the second axis (columns), resulting in a shape of (2, 8, 3). This means there are 2 arrays, each with 8 rows and 3 columns.

    np.stack(arrays, axis=2).shape:
        Stacking along axis 2 combines the arrays along the third axis (depth), resulting in a shape of (2, 3, 8). This means there are 2 arrays, each with 3 rows and 8 columns.

For the case of np.stack((x, y)), where x and y are 1D arrays, the default behavior is to stack along a new axis (axis 0), resulting in a shape of (2, 3).

# Stacking arrays in NumPy using the np.stack() function



In [8]:
import numpy as np
np.stack(arrays, axis=1).shape
(2, 8, 3)

np.stack(arrays, axis=2).shape
(2, 3, 8)

x = np.array([2, 3, 4])
y = np.array([3, 4, 5])
np.stack((x, y))

array([[2, 3, 4],
       [3, 4, 5]])

Numpy numpy.stack() function with axis parameter



In [9]:
import numpy as np
x = np.array([2, 3, 4])
y = np.array([3, 4, 5])
np.stack((x, y))


array([[2, 3, 4],
       [3, 4, 5]])

In [10]:
np.stack((x, y), axis=-1)


array([[2, 3],
       [3, 4],
       [4, 5]])

In [11]:
import numpy as np
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])
print("Vertical stacking:\n", np.vstack((a, b)))
print("\nHorizontal stacking:\n", np.hstack((a, b)))
c = [5, 6]
print("\nColumn stacking:\n", np.column_stack((a, c)))
print("\nConcatenating to 2nd axis:\n", np.concatenate((a, b), 1))



Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]

Column stacking:
 [[1 2 5]
 [3 4 6]]

Concatenating to 2nd axis:
 [[1 2 5 6]
 [3 4 7 8]]


### Broadcasting

In Mathematical operations, we may need to consider the arrays of different shapes. 


NumPy can perform such operations where the array of different shapes are involved.


For example, if we consider the matrix multiplication operation, if the shape of the two matrices is the same then this operation will be easily performed. 


However, we may also need to operate if the shape is not similar.


# Example - 1

In [12]:
import numpy as np  
a = np.array([1,2,3,4,5,6,7])  
b = np.array([2,4,6,8,10,12,14])  
c = a*b;  
print(c) 

[ 2  8 18 32 50 72 98]


# Example - 2

In [13]:
import numpy as np  
a = np.array([1,2,3,4,5,6,7])  
b = np.array([2,4,6,8,10,12,14,19])  
c = a*b;  
print(c) 

ValueError: operands could not be broadcast together with shapes (7,) (8,) 

# Broadcasting Rules

Broadcasting is possible if the following cases are satisfied.

The smaller dimension array can be appended with '1' in its shape.

Size of each output dimension is the maximum of the input sizes in the dimension.

An input can be used in the calculation if its size in a particular dimension matches the output size or its value is exactly 1.

If the input size is 1, then the first data entry is used for the calculation along the dimension.

Broadcasting can be applied to the arrays if the following rules are satisfied.

All the input arrays have the same shape.

Arrays have the same number of dimensions, and the length of each dimension is either a common length or 1.

Array with the fewer dimension can be appended with '1' in its shape.

# Example -3


In [21]:

import numpy as np  
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])  
b = np.array([2,4,6,8])  
print("\nprinting array a..")  
print(a)
print(a.shape)


print("\nprinting array b..")  
print(b)  
print(b.shape)
print("\nAdding arrays a and b ..")  
c = a + b;  
print(c) 
print(c.shape)



printing array a..
[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]
(3, 4)

printing array b..
[2 4 6 8]
(4,)

Adding arrays a and b ..
[[ 3  6  9 12]
 [ 4  8 11 14]
 [12 24 45 11]]
(3, 4)


In order to broadcast, the size of the trailing axes for both arrays in an operation must either be the same size or one of them must be one.

In [ ]:
import numpy as np
a = np.array([1.0, 2.0, 3.0])
b = 2.0
print(a * b)
c = [2.0, 2.0, 2.0]
print(a * c)

[2. 4. 6.]
[2. 4. 6.]


numpy. newaxis is used to increase the dimension of the existing array by one more dimension, when used once. Thus, 1D array will become 2D array.

In [ ]:
import numpy as np 
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([0.0, 1.0, 2.0])
print(a[:, np.newaxis] + b)

[[ 0.  1.  2.]
 [10. 11. 12.]
 [20. 21. 22.]
 [30. 31. 32.]]


NumPy allows the subtraction of two Datetime values, an operation which produces a number with a time unit. ...

The arguments for timedelta64 are a number, to represent the number of units, and a date/time unit, such as (D)ay, (M)onth, (Y)ear, (h)ours, (m)inutes, or (s)econds.

Example:

In [ ]:
import numpy as np
today = np.datetime64('2017-02-12')
print("Date is:", today)
print("Year is:", np.datetime64(today, 'Y'))
dates = np.arange('2017-02', '2017-03', dtype='datetime64[D]')

Date is: 2017-02-12
Year is: 2017


In [ ]:
print("\nDates of February, 2017:\n", dates)
print("Today is February:", today in dates)
dur = np.datetime64('2017-05-22') - np.datetime64('2016-05-22')
print("\nNo. of days:", dur)
print("No. of weeks:", np.timedelta64(dur, 'W'))
a = np.array(['2017-02-12', '2016-10-13', '2019-05-22'], dtype='datetime64')
print("\nDates in sorted order:", np.sort(a))


Dates of February, 2017:
 ['2017-02-01' '2017-02-02' '2017-02-03' '2017-02-04' '2017-02-05'
 '2017-02-06' '2017-02-07' '2017-02-08' '2017-02-09' '2017-02-10'
 '2017-02-11' '2017-02-12' '2017-02-13' '2017-02-14' '2017-02-15'
 '2017-02-16' '2017-02-17' '2017-02-18' '2017-02-19' '2017-02-20'
 '2017-02-21' '2017-02-22' '2017-02-23' '2017-02-24' '2017-02-25'
 '2017-02-26' '2017-02-27' '2017-02-28']
Today is February: True

No. of days: 365 days
No. of weeks: 52 weeks

Dates in sorted order: ['2016-10-13' '2017-02-12' '2019-05-22']


### Example1:


In [ ]:
import numpy as np
a = np.arange(10, 1, -2)
print("\n A sequential array with a negative step: \n",a)
newarr = a[np.array([3, 1, 2 ])]
print("\n Elements at these indices are:\n",newarr)



 A sequential array with a negative step: 
 [10  8  6  4  2]

 Elements at these indices are:
 [4 8 6]


### Example2:


In [ ]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = x[np.array([1, 3, -3])]
print("\n Elements are : \n",arr)



 Elements are : 
 [2 4 7]


### Example3:


In [ ]:
import numpy as np
a = np.array([[1 ,2 ],[3 ,4 ],[5 ,6 ]])
print(a[[0 ,1 ,2 ],[0 ,0 ,1]])

[1 3 6]
